FROM node:20.12.2

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/package*.json ./
RUN npm ci --no-audit --no-fund

COPY app/. .
RUN npm run build

CMD ["npm", "start"]
