FROM node:20.12.2

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci --no-audit --no-fund

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
